version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
